/// Generated by AssetsRefGenerator on 2022/03/24
class Res {
  static const String bg_wood = "assets/img/bg_wood.jpeg";
  static const String huashu = "assets/img/huashu.png";
  static const String shafa = "assets/img/shafa.png";
  static const String shouji = "assets/img/shouji.png";
  static const String shuihu = "assets/img/shuihu.png";
  static const String shuijingqiu = "assets/img/shuijingqiu.png";
  static const String xiaoxiong = "assets/img/xiaoxiong.png";
}
